### ISSUE TITLE
examples for how to do type -> term reflection in haskell

### ISSUE THREAD

**Issue by cartazio** [emilypi/group-theory#5]
lets assume we have the following interface from the `reflection` package
```haskell 

class Reifies s a | s -> a where
  -- | Recover a value inside a 'reify' context, given a proxy for its
  -- reified type.
  reflect :: proxy s -> a
```

```haskell
data Peano = Z | S Peano

data SingeltonPeano (x ::  Peano)  where 
      SingZ :: SingeltonPeano 'Z  -- we have to do those ticks for promoted constructors right?
      SingS :: SingeltonPeaon x -> SingeltonPeano ('S x )

instance Reifies 'Z (SingeltonPeano 'Z) where 
   reflect _ = SingZ 
 
instance Refifies x (SingeltonPeano  x)  => Reifies ('S x) (SingeltonPeano ('S x)) where 
   reflect _ = SingS (reflect Proxy) 

```

**Comment by cartazio** [comment]
this is all stuff i think was orginally due to a nice writeup from conor mcbride  https://www.semanticscholar.org/paper/Faking-it%3A-Simulating-dependent-types-in-Haskell-McBride/680dc58ff141bb6bbc8cc223bb78081e903b3838

**Comment by emilypi** [comment]
Thanks @cartazio - I'm closing this cuz it's not relevant for _this_ package anymore, but I'll keep it in mind for when we do modular arithmetic.
